# Generated by Django 5.2.8 on 2025-12-02 19:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='short_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
