# Generated by Django 5.2.8 on 2026-03-16 13:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blogpagegalleryimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="intro",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
